version: "3"
services:
  fastapi:
    build:
      context: .
    container_name: fastapi_api_project
    volumes:
      - ./src:/app/code
    ports:
     - 5000:80
    networks:
      - dev

networks:
  dev: